FROM python:3.13.7

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .
COPY producer.py .
COPY load_data.py .
COPY data/ ./data/

CMD ["python", "main.py"]
